"""
01_preprocessing.py
====================
Preprocessing pipeline: paimon-moe-local-data.json -> data_clean.csv

Converts the raw Paimon.moe export (Genshin Impact wish/gacha history) into
one tidy table (one row = one pull) ready for EDA & the dashboard
(Total Pull, Timeline, Pity Distribution, Win/Lose 50-50, Top
Character/Weapon, Banner Performance, Luck Score, etc.).

Input:
    data/paimon-moe-local-data.json   -> raw export
    data/char_full.json               -> id -> {name, rarity} lookup for characters
    data/weapon_full.json             -> id -> {name, rarity} lookup for weapons
    (both lookup files above are generated by 00_fetch_rarity_lookup.py --
    run that script first before this one)

Output:
    data/data_clean.csv            -> default, all UIDs combined
    data/data_clean_<uid>.csv      -> when run with --uid <uid>

Usage:
    python3 01_preprocessing.py                # all accounts -> data_clean.csv
    python3 01_preprocessing.py --list-uid      # show available UIDs
    python3 01_preprocessing.py --uid 887284572 # single account -> data_clean_887284572.csv
"""

import argparse
import json
from pathlib import Path

import pandas as pd

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"

RAW_PATH = DATA_DIR / "paimon-moe-local-data.json"
CHAR_LOOKUP_PATH = DATA_DIR / "char_full.json"
WEAPON_LOOKUP_PATH = DATA_DIR / "weapon_full.json"

# Banner key -> cleaner display label
BANNER_LABELS = {
    "wish-counter-character-event": "Character Event",
    "wish-counter-standard": "Standard",
    "wish-counter-weapon-event": "Weapon Event",
    "wish-counter-beginners": "Beginners",
}

# The 'rate' field only exists on event banners (Character Event & Weapon Event)
# for 4-star and 5-star pulls, representing the rate-up/50-50 outcome:
#   0 = lost the 50/50 (got the standard/non rate-up item)
#   1 = won the 50/50 (got the rate-up item directly)
#   2 = guaranteed (got the rate-up item because the previous pull lost)
RATE_LABELS = {0: "Lose", 1: "Win", 2: "Guaranteed"}


def load_json(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def build_account_map(raw: dict) -> dict:
    """
    The raw data stores multiple accounts:
      - main (active) account -> keys WITHOUT a prefix, e.g. 'wish-counter-standard'
      - other accounts        -> keys WITH a prefix, e.g. 'account2-wish-counter-standard'
    Returns a dict:
      { account_label: {"prefix": "" / "account2-" / ..., "uid": ..., "ar": ..., "wl": ...} }
    """
    other_accounts = [a.strip() for a in raw.get("accounts", "").split(",") if a.strip()]

    accounts = {
        "main": {
            "prefix": "",
            "uid": raw.get("wish-uid"),
            "ar": raw.get("ar"),
            "wl": raw.get("wl"),
        }
    }
    for acc in other_accounts:
        accounts[acc] = {
            "prefix": f"{acc}-",
            "uid": raw.get(f"{acc}-wish-uid"),
            "ar": raw.get(f"{acc}-ar"),
            "wl": raw.get(f"{acc}-wl"),
        }
    return accounts


def rarity_and_name(item_id, item_type: str, char_lookup: dict, weapon_lookup: dict):
    lookup = char_lookup if item_type == "character" else weapon_lookup
    # BUG FIX: JSON object keys are always strings. If the export ever yields
    # item_id as an int, a direct dict lookup silently misses even though the
    # entry exists, inflating the "unmapped rarity" warning. Coerce to str.
    entry = lookup.get(str(item_id))
    if entry is None:
        return None, None
    return entry.get("rarity"), entry.get("name")


def build_rows(raw: dict, accounts: dict, char_lookup: dict, weapon_lookup: dict):
    rows = []

    for account_label, acc_info in accounts.items():
        prefix = acc_info["prefix"]

        for banner_key, banner_label in BANNER_LABELS.items():
            full_key = f"{prefix}{banner_key}"
            banner_data = raw.get(full_key)
            if not banner_data:
                continue

            pulls = banner_data.get("pulls", [])
            for pull_number, p in enumerate(pulls, start=1):
                item_id = p.get("id")
                item_type = p.get("type")  # 'character' or 'weapon'
                rarity, item_name = rarity_and_name(item_id, item_type, char_lookup, weapon_lookup)

                rate_raw = p.get("rate")
                win_50_50 = RATE_LABELS.get(rate_raw) if rate_raw is not None else None

                rows.append(
                    {
                        "account": account_label,
                        "uid": acc_info["uid"],
                        "adventure_rank": acc_info["ar"],
                        "world_level": acc_info["wl"],
                        "banner_type": banner_label,
                        "banner_code": p.get("code"),
                        "pull_number": pull_number,
                        "datetime": p.get("time"),
                        "item_id": item_id,
                        "item_name": item_name if item_name else item_id,
                        "item_category": item_type,
                        "rarity": rarity,
                        "pity": p.get("pity"),
                        "rate_raw": rate_raw,
                        "win_50_50": win_50_50,
                        "manual_input": p.get("manualInput"),
                    }
                )

    return pd.DataFrame(rows)


def postprocess(df: pd.DataFrame) -> pd.DataFrame:
    df["datetime"] = pd.to_datetime(df["datetime"], errors="coerce")

    # BUG FIX: rows whose datetime couldn't be parsed become NaT, which then
    # leaked into year_month as the literal string "NaT" with no warning.
    n_bad_datetime = df["datetime"].isna().sum()
    if n_bad_datetime:
        print(f"[WARN] {n_bad_datetime} row(s) have an unparseable datetime and were dropped.")
        df = df[df["datetime"].notna()].copy()

    df = df.sort_values(["account", "banner_type", "datetime", "pull_number"]).reset_index(drop=True)

    # derived columns (convenience for EDA)
    df["date"] = df["datetime"].dt.date
    df["year_month"] = df["datetime"].dt.to_period("M").astype(str)
    df["is_5star"] = df["rarity"] == 5
    df["is_4star"] = df["rarity"] == 4
    df["is_3star"] = df["rarity"] == 3

    # rarity with no matching lookup entry -> flag it (data quality check)
    n_unmapped = df["rarity"].isna().sum()
    if n_unmapped:
        print(f"[WARN] {n_unmapped} row(s) have no rarity mapping (unrecognized item_id).")

    return df


def parse_args():
    parser = argparse.ArgumentParser(
        description="Preprocess the paimon-moe wish export into a tidy CSV for EDA."
    )
    parser.add_argument(
        "--uid",
        type=str,
        default=None,
        help="Only process the account with this UID. Leave empty to process all accounts.",
    )
    parser.add_argument(
        "--list-uid",
        action="store_true",
        help="Show the UIDs available in the export file, then exit.",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    raw = load_json(RAW_PATH)
    accounts = build_account_map(raw)

    if args.list_uid:
        # BUG FIX: listing UIDs doesn't need the rarity lookup files, so the
        # lookup-file check below must not block this path. Handle it first.
        print("UIDs available in the export file:")
        for label, info in accounts.items():
            print(f"  - {label}: uid={info['uid']}, AR={info['ar']}, WL={info['wl']}")
        return

    if not CHAR_LOOKUP_PATH.exists() or not WEAPON_LOOKUP_PATH.exists():
        raise FileNotFoundError(
            "Rarity lookup files not found. Run first: python3 00_fetch_rarity_lookup.py"
        )

    print("Detected accounts:")
    for label, info in accounts.items():
        print(f"  - {label}: uid={info['uid']}, AR={info['ar']}, WL={info['wl']}")

    # If the user requested a specific uid, filter the account list before
    # build_rows for efficiency, and so the output file only contains that account.
    if args.uid:
        target_uid = str(args.uid)
        accounts = {
            label: info for label, info in accounts.items()
            if str(info["uid"]) == target_uid
        }
        if not accounts:
            available = ", ".join(str(info["uid"]) for info in build_account_map(raw).values())
            raise ValueError(
                f"UID '{args.uid}' not found. Available UIDs: {available}"
            )
        out_path = DATA_DIR / f"data_clean_{target_uid}.csv"
    else:
        out_path = DATA_DIR / "data_clean.csv"

    char_lookup = load_json(CHAR_LOOKUP_PATH)
    weapon_lookup = load_json(WEAPON_LOOKUP_PATH)

    df = build_rows(raw, accounts, char_lookup, weapon_lookup)
    df = postprocess(df)

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_path, index=False)

    print(f"\nTotal rows (pulls): {len(df):,}")
    print(f"Time range          : {df['datetime'].min()} -> {df['datetime'].max()}")
    print("\nPulls per banner:")
    print(df["banner_type"].value_counts().to_string())
    print("\nRarity distribution:")
    print(df["rarity"].value_counts(dropna=False).sort_index().to_string())
    print("\nWin/Lose 50-50 per rarity (event banners, 4* & 5*):")
    print(
        df[df["win_50_50"].notna()]
        .groupby(["rarity", "win_50_50"])
        .size()
        .to_string()
    )
    print(f"\nOutput file saved to: {out_path}")


if __name__ == "__main__":
    main()